set(ASSIMP_SOURCE "${CMAKE_CURRENT_SOURCE_DIR}/../shared/.deps/assimp-5.4.3")
if(NOT EXISTS "${ASSIMP_SOURCE}/CMakeLists.txt")
  message(FATAL_ERROR "Missing pinned Assimp 5.4.3. Run engine/setup.ps1 first.")
endif()
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE BOOL "" FORCE)
set(ASSIMP_INSTALL OFF CACHE BOOL "" FORCE)
set(ASSIMP_WARNINGS_AS_ERRORS OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_ZLIB ON CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_OBJ_IMPORTER ON CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_GLTF_IMPORTER ON CACHE BOOL "" FORCE)
set(ASSIMP_NO_EXPORT ON CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_DRACO OFF CACHE BOOL "" FORCE)
set(ASSIMP_INJECT_DEBUG_POSTFIX OFF CACHE BOOL "" FORCE)
add_subdirectory("${ASSIMP_SOURCE}" assimp EXCLUDE_FROM_ALL)
add_library(lab_model_assets STATIC src/model_asset.cpp src/model_image.cpp)
target_include_directories(lab_model_assets SYSTEM PRIVATE "${ASSIMP_SOURCE}/contrib/stb")
target_link_libraries(lab_model_assets PRIVATE assimp::assimp)
add_executable(NVMatrixEngineModelAssetTest tests/model_asset.cpp)
target_link_libraries(NVMatrixEngineModelAssetTest PRIVATE lab_model_assets)
enable_testing()
add_test(NAME lab_model_assets COMMAND NVMatrixEngineModelAssetTest)
